### ISSUE TITLE
Arabic GUI

### ISSUE THREAD

**Issue by iru2x** [prateekmedia/pstube#102]
Just installed now and text is in arabic and RTL, while  my region is european. WTF? How can I put language to english?

![image](https://github.com/prateekmedia/pstube/assets/133756704/d63ff23c-7524-4947-9fc6-ce50708b1bbb)

**Comment by prateekmedia** [comment]
I guess you are using old version

**Comment by iru2x** [comment]
Yes, currently 2.0.0 flatpak version on Zorin OS which is the latest they offer in it's store...seems this distro is a bit outdated. 

I thought flatpak was always on latest version. I guess I was wrong, my bad. Apologies for opening this issue.

**Comment by iru2x** [comment]
Just one last request: Could you upload flatpak to latest version please?

**Comment by janxkoci** [comment]
I have the same problem, can we get a new release as flatpak, please?
