### ISSUE TITLE
App strings in Arabic

### ISSUE THREAD

**Issue by comradekingu** [prateekmedia/pstube#23]
Downloaded 1.1.0 from IzzyOnDroid
Default locale nb_NO;nn_NO;da;se

Don't know how to turn it off ;)

**Comment by prateekmedia** [comment]
You downloaded this app from IzzyOnDroid? I haven't published it there.

**Comment by wdkevonfernando** [comment]
I have the same issue on Linux with version 2.0.0. It would be nice to keep this issue open until a workaround or fix has been implemented. In doing so, users who come here will not be confused.

**Comment by dCo3lh0** [comment]
i have the same problem, with your appimage pool last version and pstube too. Both shows in arabic, so i use the version before the latest

**Comment by prateekmedia** [comment]
Anyone facing this can try the new nightly version

**Comment by Raitsa** [comment]
Nightly fixed android version ok 👍

**Comment by ju1ius** [comment]
FYI, the issue is present on the latest stable flatpak release from flathub.
