### ISSUE TITLE
(Desktop) Video playback is missing

### ISSUE THREAD

**Issue by ShinjuSenju** [prateekmedia/pstube#28]
Loved your concept..UI is clean and looks nice
However, Video playback isn't working (stuck on thumbnail, seems it isn't implemented yet)...
Video playback like newpipe client.
And an option to switch between invidous 
(+inbuilt instance selecter/checker) and newpipe api
Hope to see these features in future :)

**Comment by janTaja** [comment]
video playback isn’t working because youtube changed something which broke it and the app hasn't been updated to fix that yet

**Comment by prateekmedia** [comment]
@janTaja No, we current don't have video playback at all, I will try to add it in the upcoming versions.

**Comment by janTaja** [comment]
ahh, sorry then! i was sure it was there before for some reason...

**Comment by prateekmedia** [comment]
I have added video playback for android/IOS/Web you can test it here:
https://github.com/prateekmedia/flutube/releases/continuous/

**Comment by shuvashish76** [comment]
> 2. Pitch(pure black) theme
requested here #26 

@ShinjuSenju Please create multiple separate issues for separate feature_requests/suggestions & do search them if such exist before :)

**Comment by prateekmedia** [comment]
Fixed on Windows, please try latest development build.
