### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by enessgokalp** [prateekmedia/pstube#53]
The app not showing comments

**Comment by prateekmedia** [comment]
Hi, To begin with please answer the following:

What is your OS?
One video or all video don't show comments?
Send a screenshot

**Comment by enessgokalp** [comment]
Hi, my OS is android
All videos don't show comments
![Screenshot_20220505-175158](https://user-images.githubusercontent.com/57983747/166951045-b523cf9e-451a-4ad9-92dd-c81eed3afb05.jpg)
