### ISSUE TITLE
[Question] Piped API instead of YoutubeExplodeDart

### ISSUE THREAD

**Issue by kevonfernando** [prateekmedia/pstube#62]
Why is this project not making full use of the Piped API? This would allow to remove a dependency. Also it has support for SponsorBlock.

**Comment by wdkevonfernando** [comment]
Me neither, but I found a [documentation](https://piped-docs.kavin.rocks/docs/api-documentation/) for it and it seemed to do quite similar things to YouTubeExplode. I’m also unfamiliar with dart though I will try my best if you wish to use only the Piped API.

**Comment by Terkyz** [comment]
Is there anything new with this? It would be absolutely great to have Piped/Invidious support within PSTube, mainly because I don't like to rely on or use any Google services..

**Comment by prateekmedia** [comment]
Actually we have shifted quite a lot of Code to piped, but I guess some code is still using youtube_explode_dart
