### ISSUE TITLE
CI Builds

### ISSUE THREAD

**Issue by enessgokalp** [prateekmedia/pstube#68]
Can you add ci build to the actions?

**Comment by prateekmedia** [comment]
We already have [development build](https://github.com/prateekmedia/pstube/releases/continuous/) in release, why are builds in actions needed?

**Comment by enessgokalp** [comment]
Example you don't add apk with latest changes but ci builds is automatic

**Comment by prateekmedia** [comment]
The app in development build is the latest and is pushed automatically by the CI, if you are asking that.

**Comment by enessgokalp** [comment]
![Screenshot_20220622-183423](https://user-images.githubusercontent.com/57983747/175072403-84336f48-0604-4fca-985d-1cccfc2b265a.jpg)
Example this changes not added to nightly build. If you can add apk to actions we can test latest changes

**Comment by prateekmedia** [comment]
You can check the latest development builds, thanks!
