### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by venkat2305** [prateekmedia/pstube#71]
1.unable to install in windows 10. Is there any guide?
2.will you add 4k video downloading and playback with sound.
3. do you plan to add oled theme?
4. do you plan to add sign in option?

**Comment by prateekmedia** [comment]
1) Windows Version is fixed now, check nightly releases from README
2) Eventually yes
3) Yes
4) Not in the short term, Maybe in future using some OAuth stuff, but Out of Scope for now
