### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by senolfndk** [prateekmedia/pstube#74]
https://user-images.githubusercontent.com/52818836/184344264-3601e378-afe5-412d-b428-63a0b5eb9952.mp4
😒

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/184344394-2396d74c-bc7c-465d-98d2-5945b6915bca.mp4

**Comment by prateekmedia** [comment]
Windows 11, right? Use the nightly build from Readme, Windows version is like in alpha stage right now

**Comment by senolfndk** [comment]
> Windows 11, değil mi? Readme'nin gece derlemesini kullanın, Windows sürümü şu anda alfa aşamasında gibidir

yes

**Comment by senolfndk** [comment]
I checked the nightly compilation section, the file does not open, can you give the file link?

**Comment by prateekmedia** [comment]
If it doesn't work then I will check again:
https://github.com/prateekmedia/pstube/releases/continuous/

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/184407955-c8b57e3d-1fc6-4758-a202-7bedee600ac4.mp4
videos are not playing

**Comment by prateekmedia** [comment]
I know that, I am looking to solve it somehow

**Comment by senolfndk** [comment]
ok
