### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by KalpanaChetan** [prateekmedia/pstube#79]
![Screenshot_2022-09-08_11-56-29](https://user-images.githubusercontent.com/112402936/189049949-959e56e4-f1b7-4acd-b6f8-6c56c7248dba.png)

![Screenshot_2022-09-08_11-57-56](https://user-images.githubusercontent.com/112402936/189050179-c9fa1faf-8bbf-42ee-b0ec-318bb57833fc.png)

**Comment by prateekmedia** [comment]
Who said you to used the Nightly build?

**Comment by KalpanaChetan** [comment]
ओके

**Comment by KalpanaChetan** [comment]
![Screenshot_20220908-125124](https://user-images.githubusercontent.com/112402936/189060385-fa812a1c-197a-4f5a-999e-b40c473eda8f.jpg)


![Uploading Screenshot_20220908-125148.jpg…]()

**Comment by KalpanaChetan** [comment]
Version 2.6.0

**Comment by KalpanaChetan** [comment]
![Screenshot_20220908-125148](https://user-images.githubusercontent.com/112402936/189061016-98585ee2-8082-45f6-8da5-0b2e5d9b2eda.jpg)

**Comment by prateekmedia** [comment]
Let me see

**Comment by KalpanaChetan** [comment]
Pstube window 2.6.0
Pstube window continuous 

![Screenshot (32).png](https://user-images.githubusercontent.com/112402936/198929772-b5fdea68-dcdc-4a0b-ad60-80d80fe3ab1e.png)




![Screenshot (43).png](https://user-images.githubusercontent.com/112402936/198929781-2f737137-d9ff-4ab5-ac94-d43889e11c07.png)



![Screenshot (44).png](https://user-images.githubusercontent.com/112402936/198929791-5716de7f-ac17-4f92-8351-5a12d500ea66.png)


![Screenshot (45).png](https://user-images.githubusercontent.com/112402936/198930017-f2ca6f40-40b0-4974-8f11-6bd809ba332b.png)

**Comment by prateekmedia** [comment]
Fixed in latest development build, use exe
