### ISSUE TITLE
Incorrect cmake version while running in debug mode

### ISSUE THREAD

**Issue by bohrasankalp** [prateekmedia/pstube#80]
Incorrect version of cmake is identified with message. While I have version `3.24.1` for cmake on linux system.

```
This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:19 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.10.2
```

Tried with `flutter clean`. Rebuilding for `linux platform` has also been unsuccessful attempt.

**Comment by prateekmedia** [comment]
Are you sure you are on the latest cmake? Can you run and confirm the version by `cmake --version`

**Comment by bohrasankalp** [comment]
I have correct version installed that is latest, somehow I believe vlc and libvlc-dev is not installed that might creating problem. I couldn't find libvlc-dev though.
