### ISSUE TITLE
PSTube triggers APPCRASH on Windows

### ISSUE THREAD

**Issue by davitof** [prateekmedia/pstube#97]
Windows 11 64 bits, PSTube 2.6.0

Each time I try to load PSTube, nothing happens apart from a short throbber. Using Process Monitor, I see that PSTube triggers WERFault. In the Event Viewer, I see that WERFault reports an APPCRASH.

FWIW, I checked PSTube 2.0.0. It does not crash, I can see the PSTube process in Process Explorer, but I never see any window either. I have no idea what is happening with version 2.0.0.

I guess you'll need more info, but I am unable to guess what.

**Comment by solnyshok** [comment]
2.6 same here on W10x64

**Comment by prateekmedia** [comment]
Please try Nightly version

**Comment by davitof** [comment]
Thanks. I am not at home presently, but I'll try as soon as I come back.

**Comment by daoktar** [comment]
In nightly build search and video page doesn't work. 
![pstube_M1ObXbBHUI](https://github.com/prateekmedia/pstube/assets/18519029/3bdd3780-e60e-4d24-bc29-73db85425a55)
![pstube_jIcg4gJ0GM](https://github.com/prateekmedia/pstube/assets/18519029/d61c0198-690e-4ab0-ab6a-c1ca6ddb044f)

**Comment by prateekmedia** [comment]
Atleast there is no crash, I am working on other things.
